### ISSUE TITLE
File Inputs Break Routing

### ISSUE THREAD

**Issue by hleinone** [olivernn/davis.js#14]
For instance in the Greeter application replacing the `<input type="text" name="name">` with `<input type="file" name="name">` causes the routing for `this.post('/person', ...)` not to get fired at all. All other types of inputs work as expected.

**Comment by olivernn** [comment]
The issue you are seeing is because jQuery's `serializeArray` method ignores file inputs.  Davis uses this method to convert a form into a request object.

This means that the problem is actually when a form is submitted without any fields, which is a fairly simple bug fix. I'll do a patch release shortly to address this.

Handling file inputs is another issue I think. Are you trying to access the file object inside the route handler?  I think some kind of Davis extension could be created that would automatically convert the file input from a form into a file object within the req params.  However I don't think this is something that should be in the core. I'd be interested to hear your thoughts on this though.

**Comment by olivernn** [comment]
I've pushed a new release that should mean that forms with just a file input will be routed correctly.  The file input will not be present in the request params because it cannot be serialized.

**Comment by hleinone** [comment]
I guess I'm fine with that for now. I can always read the file data from the DOM elements. Of course a Davis extension providing the files as req params would be really neat.

**Comment by olivernn** [comment]
There are two problems to overcome with having file data available on the request;

1) The File API is not widely supported as of yet, although as long as this is an extension I don't think that is a major issue.

2) A request object is pushed into the browser history stack so that it can be popped out later when navigating with the back and forward buttons.  I'm not sure easy it is to reliably serialise a File object into the history stack.

It might be worth doing some investigation on point 2.  Also currently Davis doesn't support custom form serializers, but this should be very trivial to do.  If you get anywhere with this let me know, I'd be interested to see this kind of thing available as some kind of plugin / extension.
