### ISSUE TITLE
Rethrown Errors give a difficult stacktrace

### ISSUE THREAD

**Issue by s6577t** [olivernn/davis.js#28]
When application code throws an exception, Davis catches and rethrows the exception. The Chrome console reports the exception as coming from Davis which it technically does, it would be more useful if the original stack trace was used.

**Comment by olivernn** [comment]
I think this is actually a [bug](http://code.google.com/p/chromium/issues/detail?id=60240) with Chrome.  The error is being re-thrown in Davis rather than a new Error being created.  Other browsers, including Safari, show the correct stack trace.  I'm not sure there is a way to work around this currently unfortunately.
