### ISSUE TITLE
Use of forEach breaks in IE8

### ISSUE THREAD

**Issue by jbaudanza** [olivernn/davis.js#3]
In particular, this piece of router.js code fails to load:

```
var verbs = ['get', 'post', 'put'];
verbs.forEach(function (verb) {
  self[verb] = function (path, handler) {
    self._routeCollection.push(new Davis.Route (verb, path, handler));
  }
})
```

This generates a `Object doesn't support this property or method` error when the script loads.

forEach is a recent addition to ECMAscript, so this is probably an issue in other browsers as well.

There's a few ways to handle this.  Let me know what you think.  I'd be happy to put together a pull request.

**Comment by olivernn** [comment]
Good catch, Davis.js isn't currently supported in IE because there is no pushState support, however it certainly shouldn't raise any errors in those browsers.

I just checked and currently Davis is using forEach, map, filter & every, all of which are not available in IE.  Ordinarily I would suggest using something like [augment.js](http://augmentjs.com/) however I don't think it is acceptable for Davis to start augmenting built in types.

Instead I think implementing these methods in some kind of utils module is the way to go.  Ideally they should use native implementations where ever possible.

```
 var verbs = ['get', 'post', 'put'] 
 Davis.utils.forEach(verbs, function (verb) {
    self[verb] = function (path, handler) {
      self._routeCollection.push(new Davis.Route (verb, path, handler))
    }
 })
```

**Comment by jbaudanza** [comment]
Sounds good.  I'll put together a pull request

**Comment by olivernn** [comment]
I actually made a start, I've mostly been using the code & tests straight from [augment.js](http://augmentjs.com), I've pushed what I have so far in this [branch](https://github.com/olivernn/davis.js/tree/utils).

**Comment by jbaudanza** [comment]
ok cool.  Great library by the way.  I'm going to be deploying it on www.beatlab.com shortly.

**Comment by olivernn** [comment]
The latest release introduces a utils module which provides fallbacks for browsers such as IE which do not provide native implementations of forEach etc.  Davis.js will now fail gracefully in IE.

Glad you like the library and have found it useful!
