### ISSUE TITLE
How to handle traditional form redirects 

### ISSUE THREAD

**Issue by agentgt** [olivernn/davis.js#36]
[This is not a bug]

How are people handling redirects?

My app for non pushstate browsers makes a request and gets back HTML. For pushstate it gets back the model as JSON and renders it with Mustache. 

Now the only issue is that traditional FORMS you want to do a redirect after the POST. Although it sort of works my AJAX request for the JSON model will follow the redirect after POST (and then get served JSON) but strange things happen. Firebug for one gets screwed up. I also still have to manually tell the browser to redirect for pushstate. 

So I'm thinking of just serving the form POST for pushstate browsers as JSON object that says redirect with out actually doing the redirect. Then do the redirect with the Davis (ie manually do the redirect).

Is that sound good? What do others do.

**Comment by olivernn** [comment]
I'm not entirely sure I understand the issue, however for reference this is how I would suggest handing redirects from forms:

Say you have a resource on your server for notes at `/notes`.  You have a form to create a new note and a route to show a note, so your Davis app might look something like this:

```
var app = Davis(function () {
  this.get('/notes/:id', function (req) {
    var note = Note.find(req.params['id'])
    render(note) // however you go about rendering your note
  })

  this.note('/notes', function (req) {
    var note = new Note (req.params['note'])
    note.save(function () {
      req.redirect('/notes/' + note.id)
    })
  })
})
```

I'm assuming you have some kind of model layer in your JavaScript which handles the AJAX request etc and you keep all your data in the client so that the `Note.find` isn't making a request to the server.

So when you do an AJAX note your server redirects to the show for that note and you get back a JSON representation of the note you just created.  In your Davis app you then redirect to a show route for your note and it is displayed the same way as any other note.

You might also want to look at the [example Davis app](https://github.com/olivernn/notepad) which works exactly like this .

Does that make sense?

**Comment by agentgt** [comment]
I'm not really using Davis.js as much for a true Single Page application where the model is stored entirely on the client. I'm actually using it to do something like the old school Hijax approach where you reload part of the page based on request.  An example of this is here: http://duganchen.ca/single-page-web-app-architecture-done-right/

Now back to the issue of redirect. It turns out redirects are done automatically by the browser for XHR requests and there is no way of knowing in Javascript that you were just redirected (that is I want the server side to decide if I need to redirect contrary to your example).

So my solution is for the server not to do a redirect for clients that request "application/json" but instead just send a JSON back to tell davis to do the redirect:

```
        davis.post(url, function(r) {
            var data = r.params;
            var done = false;
            $.post(url, data, function(response) {
                if (response.redirect) {
                    r.redirect(response.location);
                }
                else {
                    model = response;
                    renderBody();
                }
                done = true;
            }, 'json');
            renderWaitBody(function() { return done; });

        });
```
