### ISSUE TITLE
URLs with hostnames cause routing errors

### ISSUE THREAD

**Issue by jbaudanza** [olivernn/davis.js#5]
The Davis.Request object doesn't seem to handle full URLs with hostnames.

For example, this is OK:

``` javascript
var req = new Davis.Request({ fullPath: '/hello', method: 'get' });
Davis.location.assign(req);
```

but this causes routing errors:

``` javascript
var req = new Davis.Request({ fullPath: 'http://www.example.com/hello', method: 'get' });
Davis.location.assign(req);
```

This is only an issue for me in IE7, which unfortunately translates all hrefs into non-relative URLs.   For example:

```
>> document.write('<a href="/hello"> my link </a>')
>> $('a').attr('href')
http://www.example.com/hello
```

I solved this for myself by using a RegExp in my davis click handler to remove the http://hostname/ part.  

It is conceivable that someone might have a legitimate href link with a full URL in it.  It would be nice if Davis.Request would handle this gracefully.  Let me know if you have any thoughts on this.  I'd be happy to put together a pull request.

If you're interested, there is more information on the IE7 issue on this blog post.  http://www.glennjones.net/2006/02/getattribute-href-bug/  He presents a workaround, but it doesn't work on dynamically created elements.

**Comment by olivernn** [comment]
Interesting, I didn't know IE7 behaved that way.  I definitely agree that Davis should handle full urls gracefully.

I think the best place to do this would be when instantiating the new Davis.Request rather than in the Davis.listener.  Perhaps on [here](https://github.com/olivernn/davis.js/blob/master/src/davis.request.js#L58), this could be changed to handle when fullPath is a full url or just a path.

I'm thinking that perhaps the option name should change, since it may no longer be just a fullPath, it could legitimately be a url.

Let me know what you come up with, I'm more than happy to accept a patch to fix this.

**Comment by jbaudanza** [comment]
I submitted a pull request to strip out the hostname and port parts.  I didn't change the name of `fullPath` because I wanted to discuss some ideas with you.

I've been thinking about what the correct behavior should be if Davis encounters a full url.  Throwing away the host and protocol info seems like a bit of code smell to me.

Perhaps it would more correct for Davis to do a full page reload for URLs with hostnames, protocols, or ports that don't match the current window.location.

I would propose changing the input parameters of Davis.Request to match the format of window.location and A element nodes.  This would allow you instantiate a Request it the following ways:

``` javascript
// Programmatically make a request
var req = new Davis.Request({ pathname: '/some_resource' });
Davis.location.assign(req);

// Click Handler.
$('a.davis').click( function() {
  var req = new Davis.Request(this);
  Davis.location.assign(req);
});
```

All anchor tags have attributes for pathname, host, protocol, etc.., so the Request constructor would handle both cases the same.   The constructor would check host, protocol, port, etc with the current values on window.location.  If they were different, it would invoke a full page refresh, or call delegateToServer, or something along those lines.

Let me know what you think.  I may be inventing a use case that doesn't exist, but I think at least following the naming convention that's used on A tags would be a positive change.

**Comment by olivernn** [comment]
I wasn't aware that link elements had those properties, it certainly seems like a relatively clean way of creating a request.  Unfortunately creating requests for form submits would still need to be handled the old way but that is fine.  We'd also have to default the request method to get, since a link wont have a method property, I don't think this is a problem though.

As for being able to change the whole page location from a Davis.Request, I'm not as sure yet.

If there are links in your page that point to locations on a different domain, for example, then I think the correct way to handle those links is to make sure that Davis isn't being bound to them.  That way a 'normal' link wouldn't have to go through Davis, the browser would just handle it.

I'm not against the idea entirely, I just want to make sure that there is a good use case for this functionality before adding the complexity required to implement the feature.  Perhaps Davis could be smarter about which links it tries to bind to?

**Comment by jbaudanza** [comment]
I hadn't considered forms.  I think you're right.  Having a day to think this over, it seems kind of "science-project"ish
